export type WiktionaryWordEntry = {
  word: string
  clue: string
}

// Generated by scripts/sync-wiktionary-es.mjs
// Source: https://es.wiktionary.org (titles normalized to A-Z).
export const WIKTIONARY_ES_WORDS: WiktionaryWordEntry[] = [
  {
    "word": "ABA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AGI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AHQ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AIN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AJE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AJO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AZA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AZO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BIL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BLE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BOL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BUL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CIP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CRO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CUE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CYP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EEX",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EGS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EJO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EKS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ELO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ERA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EST",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ETA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ETE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ETH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ETO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EUX",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EZA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FEX",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FON",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FRU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HED",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEG",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HON",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IFY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IGI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IJO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ING",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IOU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IST",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IUM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IVA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IVO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JAA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JAE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAQ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KIR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KUO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KUU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LIG",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LLI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LUB",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LUM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MEJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MET",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MME",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NAK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NAM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NGE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NIK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NNE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NSA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OCA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OCH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OCO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OOB",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OON",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OSO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PIL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PUN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "QAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "QEI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "QUE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RKE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RPA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RRA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RRO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SAQ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SAW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SOL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TAP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TYE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UCH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UGH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ZOB",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ABLE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACHA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACHO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACVA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADAK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AFLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AGIR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AIDH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AIOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AJES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AJPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AKAM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AKSA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AKTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALLY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMWA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANZA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARCA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARHO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARRO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASCO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATAL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AZAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AZGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AZON",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AZOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BABA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BADE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BARO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BAYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BIOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BLOA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BOVU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CEPS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CETA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CETE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHAJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHIP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHUP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHYP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CICA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CICO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CIDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CION",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CITA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CITO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CMEL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CNAM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "COLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CULA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DERA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DGMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DICH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DOGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DORA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DUOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DURA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DWOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EGAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EGOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EHAA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ELEA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ELHA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ELOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENCO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENNE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENSE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ERAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ERIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESCO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESCU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESHR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ETAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ETOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EUPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EUSI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EWRO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EZAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EZES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FERA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FICO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FIDH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FILO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FITA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FITO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FOBO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FODO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FONA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FONO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FOON",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUPI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FURA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GAMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GAMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GATE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEBO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEYH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GONA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GONO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GONS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GORE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GORK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GORM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOWH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GUMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GUTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAII",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HDNT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEIT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HMBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HNER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HORN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HUAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IANO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IBLE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDAE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IEGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IEGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IEKR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IEME",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IGAC",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IMBA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INCI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INGI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INHA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INHO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IQUE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISCH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISCO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISHI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISME",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZCO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZEM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IZOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JAKU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JATA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JEKE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JUKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KABA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAJA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KATA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAVU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KECE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KEIT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KETI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KETL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRED",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KUDE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KUDI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KUNA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KURU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LALA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LESS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LICH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LIKE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LITO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOGY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LUBY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LULA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAAX",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAGO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAHA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MALI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MANO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MANU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MEES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MENT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MWAJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NAAL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NANE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NATA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NENE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NESS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEST",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEWN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NGAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NTIN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NYWA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ODTU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ODWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OIDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OIDE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OINA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OJHA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OKIL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OSIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OSUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OVAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OVAT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PANA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PEDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PEWG",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PEWK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PIGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLEX",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PODO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PODS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "POTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PUTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "REFU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RRAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SARA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SAVI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEMI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SENO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEWH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TORA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UODR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "USEJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UTLH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WEIK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WEKS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WEWE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YEMI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACEAE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACEUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADORA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADURA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AGILA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AKSTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALGIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMBAY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMBRE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMPAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANANA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANERA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANEUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANZAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARIUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASKYI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASUHE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATIVA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATIVO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BRTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BUNDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BYTIN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHAFU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEPP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEZA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHIPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHIPP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHOMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHOPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHYPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHYPP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CIDIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CILLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CILLO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CITAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CITOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CLADO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CRATA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CULUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DADES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DAGAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEGOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEKMT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DERAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DERMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DHANI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DHTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIEUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DONOA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DORAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DORES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DROMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DURAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DUWOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYENS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEWH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECITA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECITO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDURA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EKWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENTAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ENTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ERIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESIMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESKEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESTIY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EWROP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EYEWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FAGIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FALUW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FEMIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FERAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FEROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FICAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FICUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FILIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FITAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FITOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FOBIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FONAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FONIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FONOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FORME",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUGAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUGOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FUNGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GAMIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GANDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEYHW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOLVA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GONAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GONGA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GONOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOWES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GRAFO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GRAMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAGMN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAHTR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HANTI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HANTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEKUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HESHR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HESTI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HIEKR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HMBOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HNEWN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HNOMN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HOJOK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HREGS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HRETH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HUNAG",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HURNA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IASIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ICIOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDADE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDERO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDURA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IEGAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IEGOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IIPAY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLEI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLON",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLUI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILYAW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INSEP",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IQUES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISMUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISTAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITIVA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITIVO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JENAK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAMUA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KARIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KENAK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KERDH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KERDI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KICUG",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KMTOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KOMAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KOPEK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KREDI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRPOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRTSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KULII",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LECTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOGIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOGIE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOXIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MACKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MANIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MENTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MENTE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MENTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METRA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METRO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MINYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MNTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MORFO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NAHUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NAKTA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NAMUK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NCHIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEHUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKTH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKTM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOMIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOORI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OCLUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OGOPA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OIDEO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OINAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OINOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OKTOW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OMEGH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OQQAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORORO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAHUR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PARUA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PASUA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PATHY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PATIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PENIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PENKE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHILE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHONE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PUMUA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "REHKS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ROOKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SAHWL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEPTM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SKETI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SLNCE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SOHUL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SOHWL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SWEKS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TAHTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TAINT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TEROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TISNT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TSIKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TUULI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWERE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWILL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWONT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWOUD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UDROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "USQAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "VASKI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WASKE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WEDOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WERAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WINAQ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WLKOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YEKKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YUBUT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YURUM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ADOIRA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMBRES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANDORA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGUKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGWED",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARACHO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARQUIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATARIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVRIQA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BAHLAM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BERETI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BERTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BITANA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BUNDUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CARDIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CECITO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHEPPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHIMBA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHIPPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHUPPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CHYPPE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CISIMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CISIMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CRACIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CRATAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CULTOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DAIWER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEIUIH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEIUOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DERMIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIUIOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWMIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DOHNOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DOHTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DONCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DUHMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DUMBRE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEWES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DYEWMS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECITAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECITOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EDADES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EKUNDU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FAFINE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FAHAMU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FIKIRI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FILIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "FLEXIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GAMIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHMN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWMIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GIHWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GISLAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GNHTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GODINA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GOMBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GRAFIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAGROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAKTOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAPEDA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HARJAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HAWSOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HDONTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEGROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEKTEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HEKWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HESABU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HESHOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HNEHMN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HOKTOW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HOYNOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHANH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHANI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHANS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHMBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHNEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHNES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHNEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSONTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IDADES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENTAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IENTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IFICAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILLAEI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INGLAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAKAWA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KAUPPA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KEHROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KERDIH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KETUOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KLAWIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDMIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LANDIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LANGAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LATRIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LISTLI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LIZTLI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOCHIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOGIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "LOTODO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MANCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MANIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MEHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MENTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MERTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METRAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METRIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MIENTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTANS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOMS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTONS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOYH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOYS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKDBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NMRTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKTES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKTMS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NOKTNS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OCHMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ODWIPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OGELEA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONIEZH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONIMIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OPUHWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRIAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORRIOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAHWOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PATHIE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHOBIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHOBIE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTREH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTREY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTROM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHUMBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHUNEH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHUNES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHUNEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHWENH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHWENI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHWENS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PIGANA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PINDUA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLASIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLASTY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLOVIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PNKTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PORTUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PULIZA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RENGAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RODINA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RODITI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SATULA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SAURIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SHWENH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SHWENI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SHWENS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SUESOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SUHNUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SUHYUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TIRARE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TREYES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TSHALL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWASNT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWOULD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UIHROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "UTLHPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WEDORH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WENHOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WERCXL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "WULFAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ABANTEO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACHUELA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACHUELO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AJUBITA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ALJAYIR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMERIQA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMIENTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASRALYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVIOLUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILIDAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BRAHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BREHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CADNADO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CEFALIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CISIMAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CISIMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CLASTIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "CULTURA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DACTILO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DEKMTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIWOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DLONGOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DUGHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ECTOMIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EMBAMBA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EPILNAH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EQWADOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESCENCE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHOSH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHTIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHTOR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GEWOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HESHORH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HORARAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHAMBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HSHANEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HUNHRUZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HWIDEWH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IIPAYAA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IMIENTO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "INSEPDU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ISSIMUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IWREMWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KEJEHAK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRDOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KRUHROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KSPENTS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KUORWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MAGHIOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METIPSE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHAY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHHE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHMS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHNS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOHAD",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOSYO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOYSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKDBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKDBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKDBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTMIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NUKILIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ODTUMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ORISMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OSTERAY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLHMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLHPOH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLHQED",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLHTEJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PAHWORH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PENKTOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERHE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERMS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTERNS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRMIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTRMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTROWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHWEMBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHWENEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLASTIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PLASTIE",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RADITEI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "RODSTVO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SADULAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SAFISHA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SHWEMBI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SHWENEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "TWERENT",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACHUELAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ACHUELOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMBAYMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AMPASMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGGHOLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANTARTIQ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ATLANTIQ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BALTIJAZ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILISIMA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILISIMO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BLODIJAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BLOIJANA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BRAHTERM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DISMERDO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ELBAHREN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ERITRAYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESCENCIA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ESWATINI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESIH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESSU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHTRIH",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GNHSKETI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ILYAWMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ITYOPIYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "JANUELLA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KESEKTAL",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KETWORES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTOYOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NEKTOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ONROSMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OPUHWIPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OQQARMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OQQARQIJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "PHTROHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SADULONA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEPTMMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SUEKUROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SWEKRUHS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SWEKUROS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YEMILCEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "YUMURTKA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANGWEDMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILIDADES",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILISIMAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "BILISIMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "COMINITIO",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ELMEHCHAW",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESBIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESBOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESBOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESMIS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESMOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESOWS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "HANGUSTAS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "IWREMWIPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KEELTADAK",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MRTAHOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLHTEJPU",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ANYANOQQAR",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ARHENTINYA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "ASERBAYJAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "DIEUSPHTER",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "EPILNAHMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "GENHESOHOM",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KIMALAINEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "MEHILAINEN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "METIPSIMUS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "NDRANGHETA",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OCHMUTLHWI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OTLHQEDMEY",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEMIGIHWOS",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "AVGHANISTAN",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "KREDDEDEHTI",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "OQQARMEYQIJ",
    "clue": "Termino de Wikcionario ES"
  },
  {
    "word": "SEHMIGIHWOS",
    "clue": "Termino de Wikcionario ES"
  }
]
